### ISSUE TITLE
Information on how to install

### ISSUE THREAD

**Issue by davidjohanssonbf** [buchatsky/jinqu-ng-http#1]
Hi

Could you provide information on how to install and use this in a  brand new Angular project?

What is odata/ here?
super('odata/', new AngularHttpProvider(http));

Do we need to register it somewhere?

**Comment by buchatsky** [comment]
1. I would like the author of jinqu take over the ownership and put it together with other jinqu packages.
For the moment you can clone it and then either use [npm symlinks](https://docs.npmjs.com/cli/v8/commands/npm-link) or directly reference the cloned package location in your package.json
2. 'odata/' is a relative path to OData service. See jinqu-odata docs
3. No need to register

**Comment by davidjohanssonbf** [comment]
Thanks @buchatsky, I got it working.

**Comment by buchatsky** [comment]
Now is accessible at npmjs: [jinqu-ng-http](https://www.npmjs.com/package/jinqu-ng-http)
