### ISSUE TITLE
.inlineCount() gives NaN

### ISSUE THREAD

**Issue by davidjohanssonbf** [buchatsky/jinqu-ng-http#2]
When including `.inlineCount()` into the query the response type from jinqu changes from `Cat[]` to `Value<Cat[]> & InlineCountInfo`.

`result.inlineCount` always gives me `NaN` in this scenario.

Consider the following query:

`````
const result = await this.context.cats.inlineCount().toArrayAsync();
console.log(result.inlineCount); <- inlineCount is NaN here.
`````

Are you also able to reproduce?
Any suggestions?

**Comment by buchatsky** [comment]
It was a [jinqu-odata bug](https://github.com/jin-qu/jinqu-odata/pull/35), should be fixed in the next jinqu-odata release
